---
title: "Morphea"
author: "Thomas Vroylandt"
date: "`r format(Sys.time(), '%d/%m/%Y')`"
output: 
  html_document:
    css: "../style/style.css"
    includes:
      in_header: "../style/header.html"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)
```

<div class = "social-bar">
[`r icon::ii(name = "social-github")` ](https://github.com/tillac/morphea)
</div>

```{r import}
# packages
library(tidyverse)
library(reactable)
library(googlesheets4)
library(htmltools)

# Google Auth
gs4_deauth()

# data
data <-
  read_sheet(Sys.getenv("SHEET_PATH"),
             sheet = "tw_fav") %>%
  mutate(
    text = if_else(
      is_quote == TRUE,
      paste0(text, "\n ** ---------------- ** \n", quoted_text),
      text
    ),
    text = str_remove_all(text, "http\\S+\\s*"),
    urls_expanded_url = case_when(
      is_quote == TRUE &
        (!is.na(urls_expanded_url) &
           !is.na(quoted_urls_expanded_url)) ~   paste0(urls_expanded_url, " ", quoted_urls_expanded_url),
      is_quote == TRUE &
        (is.na(urls_expanded_url) &
           !is.na(quoted_urls_expanded_url)) ~   quoted_urls_expanded_url,
      is_quote == TRUE &
        (!is.na(urls_expanded_url) &
           is.na(quoted_urls_expanded_url)) ~   urls_expanded_url,
      TRUE ~ urls_expanded_url
    ),
    urls_expanded_url = str_trim(urls_expanded_url, "both"),
    ext_media_url = case_when(
      is_quote == TRUE &
        (!is.na(ext_media_url) &
           !is.na(quoted_ext_media_url)) ~   paste0(ext_media_url, " ", quoted_ext_media_url),
      is_quote == TRUE &
        (is.na(ext_media_url) &
           !is.na(quoted_ext_media_url)) ~   quoted_ext_media_url,
      is_quote == TRUE &
        (!is.na(ext_media_url) &
           is.na(quoted_ext_media_url)) ~   ext_media_url,
      TRUE ~ ext_media_url
    ),
  ) %>%
  select(
    link_tw,
    created_at,
    name,
    text,
    ext_media_url,
    hashtags,
    urls_expanded_url,
    favorite_count,
    retweet_count
  )
```


```{r tab_functions}
# printing functions
# bar chart
bar_chart <-
  function(label,
           width = "100%",
           height = "18px",
           fill = "#00bfc4",
           background = NULL) {
    bar <-
      div(class = "b-chart",
          style = list(
            background = fill,
            width = width,
            height = height
          ))
    label <- div(class = "hideout", format(label, big.mark = " "))
    chart <-
      div(style = list(
        flexGrow = 1,
        marginLeft = "8px",
        background = background
      ),
      bar,
      label)
    div(style = list(display = "flex", alignItems = "center"),
        chart)
  }

# img link
link_img <- function(img, nb) {
  tags$a(href = img[nb], target = "_blank", tagList(div(
    style = list(display = "inline-block", width = "100%"),
    img(src = img[nb])
  )))
}

# img printing
print_img <- function(value) {
  if (!is.na(value)) {
    # nb img
    img_list <- str_split(value, pattern = " ")[[1]]
    nb_img <- length(img_list)
    
    # 1 img
    if (nb_img == 1) {
      link_img(img_list, 1)
    }
    
    # 2 img
    else if (nb_img == 2) {
      div(class = "row",
          div(class = "column", link_img(img_list, 1)),
          div(class = "column", link_img(img_list, 2)))
    }
    
    # 3 img
    else if (nb_img == 3) {
      div(
        class = "row",
        div(class = "column", link_img(img_list, 1)),
        div(class = "column", link_img(img_list, 2),
            link_img(img_list, 3))
      )
    }
    
    # 4 img
    else if (nb_img >= 4) {
      div(
        class = "row",
        div(class = "column", link_img(img_list, 1),
            link_img(img_list, 2)),
        div(class = "column",
            link_img(img_list, 3),
            link_img(img_list, 4))
      )
    }
  }
}

# link_list
link_list_url <- function(value) {
  if (!is.na(value)) {
    link_list <- str_split(value, pattern = " ")[[1]]
    
    tagList(lapply(link_list, function(x) {
      div(tags$a(
        href = x,
        target = "_blank",
        str_remove_all(x, "https://|http://")
      ))
    }))
  }
}
```

```{r tab}
# table
reactable(
  data,
  filterable = TRUE,
  defaultPageSize = 100,
  defaultColDef = colDef(headerClass = "header"),
  columns = list(
    created_at = colDef(
      name = "Date",
      cell = function(value) {
        format(value, format = "%d/%m/%Y \n%H:%M")
      }
    ),
    name = colDef(name = "Account"),
    text = colDef(name = "Text",
                  minWidth = 200),
    hashtags = colDef(name = "Hashtags", minWidth = 100),
    urls_expanded_url = colDef(name = "Links",
                               cell = link_list_url,
                               html = TRUE),
    link_tw = colDef(
      name = "",
      filterable = FALSE,
      minWidth = 10,
      cell = function(value) {
        tags$a(href = value, target = "_blank", "\u2693")
      }
    ),
    ext_media_url = colDef(
      name = "Media",
      filterable = FALSE,
      cell = print_img,
      minWidth = 180
    ),
    favorite_count = colDef(
      name = "Fav nb.",
      filterable = FALSE,
      cell = function(value) {
        width <-
          paste0(log(value) / log(max(data$favorite_count)) * 100, "%")
        bar_chart(value, width = width, fill = "#741336")
      }
    ),
    retweet_count = colDef(
      name = "Fav RT",
      filterable = FALSE,
      cell = function(value) {
        width <-
          paste0(log(value + 1) / log(max(data$retweet_count)) * 100, "%")
        bar_chart(value, width = width, fill = "#606c71")
      }
    )
  )
)
```
